spring:
  cloud:
    gateway:
      default-filters:
        - name: AccessibleAddressFilter
          args:
            addresses: 0:0:0:0:0:0:0:1
      routes:
        - id: find
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/book/find/**