spring:
  application:
    name: book-factory
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}
        service-name: ${spring.application.name}
        port: 8090

# properties for management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"

# properties for server
server:
  undertow:
    accesslog:
      dir: logs/
      enabled: true
    threads:
      io: 2
      worker: 4
  port: 8090
  # properties for kafka
logging:
  file:
    name: logs/${spring.application.name}.log